import { createFileRoute, Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { useState } from "react";
import { Scissors, Search, ArrowRight, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteHeader } from "@/components/site-header";
import { publicShopsOptions } from "@/lib/shops.functions";
export const Route = createFileRoute("/clients")({ loader: ({context}) => context.queryClient.ensureQueryData(publicShopsOptions()), head: () => ({meta:[{title:"Trouver un barbier — NextChair"},{name:"description",content:"Choisissez un salon et rejoignez sa file d’attente."},{property:"og:title",content:"Votre prochain barbier — NextChair"},{property:"og:description",content:"Les salons NextChair vous accueillent sans rendez-vous."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}]}), component:Clients });
function Clients(){const {data:shops}=useSuspenseQuery(publicShopsOptions());const [search,setSearch]=useState("");const filtered=shops.filter(shop=>shop.name.toLocaleLowerCase("fr").includes(search.toLocaleLowerCase("fr")));return <><SiteHeader/><main className="mx-auto max-w-6xl px-5 py-10"><p className="text-sm font-semibold uppercase text-accent">Espace client</p><h1 className="mt-2 font-display text-5xl">Votre prochain barbier.</h1><div className="relative mt-7 max-w-lg"><Search className="absolute left-3 top-3.5 h-5 w-5 text-muted-foreground"/><Input aria-label="Rechercher un salon" placeholder="Rechercher un salon…" value={search} onChange={e=>setSearch(e.target.value)} className="h-12 pl-11"/></div><div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(shop=><article key={shop.id} className="flex flex-col rounded-lg border bg-card p-6"><div className="flex items-center justify-between"><Scissors className="h-7 w-7 text-primary"/><span className="text-xs text-muted-foreground">Sans rendez-vous</span></div><h2 className="mt-5 break-words font-display text-3xl">{shop.name}</h2><p className="mb-6 mt-2 flex items-center gap-2 text-sm text-muted-foreground"><Clock className="h-4 w-4"/>{shop.avg_cut_minutes} min par coupe</p><Button className="mt-auto w-full" asChild><Link to="/s/$slug" params={{slug:shop.slug}}>Prendre mon tour<ArrowRight/></Link></Button></article>)}</div>{!filtered.length&&<p className="py-12 text-center text-muted-foreground">{search?"Aucun salon ne correspond à votre recherche.":"Aucun salon disponible pour le moment."}</p>}</main></>;}
