import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Scissors, QrCode, Users, Clock } from "lucide-react";
import { Button } from "@/components/ui/button";
import { SiteHeader } from "@/components/site-header";
import { useAuth } from "@/lib/auth-context";
import photo from "@/assets/barber-shop.jpg";
export const Route = createFileRoute("/")({ head: () => ({ meta: [{title:"NextChair — Votre tour chez le barbier"},{name:"description",content:"L’espace des barbiers et de leurs clients : salons, file d’attente en direct et accès par QR code."},{property:"og:title",content:"NextChair — Votre tour chez le barbier"},{property:"og:description",content:"Un salon bien organisé. Des clients qui attendent sereinement."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"}] }), component: Index });
function Index(){const {user}=useAuth();return <><SiteHeader/><main>
 <section className="relative isolate min-h-[440px] overflow-hidden bg-secondary text-secondary-foreground md:min-h-[500px]">
 <img src={photo} alt="Un barbier réalise une coupe dans un salon moderne" width={1536} height={1024} fetchPriority="high" className="absolute inset-0 h-full w-full object-cover object-center"/>
 <div className="hero-shade absolute inset-0"/>
 <div className="relative mx-auto max-w-6xl px-5 py-14 md:py-20"><p className="mb-5 flex items-center gap-2 text-sm font-semibold uppercase"><span className="h-2 w-2 rounded-full bg-primary"/>Pour les barbiers. Pour leurs clients.</p><h1 className="font-display text-7xl leading-none md:text-8xl">NextChair<span className="text-primary">.</span></h1><p className="mt-4 max-w-md text-2xl font-medium">Votre tour chez le barbier.<br/>Sans perdre votre temps.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" className="h-12" asChild><Link to={user?"/account":"/auth"}>Je suis barbier<Scissors/></Link></Button><Button size="lg" variant="outline" className="h-12 border-secondary-foreground/40 bg-secondary/60 text-secondary-foreground hover:bg-secondary" asChild><Link to="/clients">Je suis client<ArrowRight/></Link></Button></div></div>
 </section>
 <section className="mx-auto max-w-6xl px-5 py-10"><div className="flex flex-wrap items-end justify-between gap-3"><div><p className="text-xs font-semibold uppercase text-primary">Chacun son espace</p><h2 className="mt-2 font-display text-4xl">Une belle coupe commence ici.</h2></div><span className="text-sm text-muted-foreground">Moins d’attente. Plus de style.</span></div><div className="mt-7 grid gap-7 md:grid-cols-2"><article className="rounded-lg border bg-card p-6"><Scissors className="h-7 w-7 text-primary"/><h3 className="mt-4 font-display text-3xl">Espace barbier</h3><p className="mt-2 text-muted-foreground">Votre salon, votre file d’attente et vos clients au même endroit.</p><div className="mt-5 flex flex-wrap gap-5 text-sm"><span className="flex items-center gap-2"><Users className="h-4 w-4 text-primary"/>File en direct</span><span className="flex items-center gap-2"><QrCode className="h-4 w-4 text-primary"/>QR du salon</span></div><Button variant="link" className="mt-5 px-0" asChild><Link to={user?"/account":"/auth"}>Accéder à mon espace<ArrowRight/></Link></Button></article><article className="rounded-lg border bg-card p-6"><Users className="h-7 w-7 text-accent"/><h3 className="mt-4 font-display text-3xl">Espace client</h3><p className="mt-2 text-muted-foreground">Choisissez votre barbier et retrouvez votre place dans la file.</p><div className="mt-5 flex flex-wrap gap-5 text-sm"><span className="flex items-center gap-2"><Clock className="h-4 w-4 text-accent"/>Attente estimée</span><span className="flex items-center gap-2"><Scissors className="h-4 w-4 text-accent"/>Sans rendez-vous</span></div><Button variant="link" className="mt-5 px-0" asChild><Link to="/clients">Trouver un salon<ArrowRight/></Link></Button></article></div></section>
 </main><footer className="border-t px-5 py-5 text-center text-sm text-muted-foreground">NextChair · Le rendez-vous des sans rendez-vous.</footer></>;}
