import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteHeader } from "@/components/site-header";
import { supabase } from "@/integrations/supabase/client";
export const Route = createFileRoute("/reset-password")({ head: () => ({ meta: [{ title: "Nouveau mot de passe — NextChair" }, { name: "description", content: "Réinitialisez votre mot de passe NextChair." }, { property: "og:title", content: "Nouveau mot de passe — NextChair" }, { property: "og:description", content: "Retrouvez l’accès à votre compte." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }), component: Reset });
function Reset() {
 const [allowed, setAllowed] = useState(false); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState("");
 useEffect(() => { const recovery = window.location.hash.includes("type=recovery"); if (recovery) sessionStorage.setItem("nc-recovery", "yes"); setAllowed(recovery || sessionStorage.getItem("nc-recovery") === "yes"); }, []);
 async function save(e: React.FormEvent) {e.preventDefault();setError("");if(password!==confirm){setError("Les mots de passe ne correspondent pas.");return;}setBusy(true);try{const {error}=await supabase.auth.updateUser({password});if(error)throw error;setDone(true);sessionStorage.removeItem("nc-recovery");}catch{setError("Le lien a expiré ou le mot de passe est invalide. Demandez un nouveau lien.");}finally{setBusy(false);}}
 return <><SiteHeader/><main className="mx-auto max-w-md px-5 py-12"><h1 className="font-display text-4xl">Nouveau mot de passe</h1>{done?<><p className="my-5">Votre mot de passe a été mis à jour.</p><Button asChild><Link to="/account">Mon espace</Link></Button></>:!allowed?<><p className="my-5">Ouvrez le lien de réinitialisation reçu par e-mail.</p><Button asChild><Link to="/auth">Retour à la connexion</Link></Button></>:<form onSubmit={save} className="mt-6 space-y-4"><label htmlFor="new-password" className="block">Nouveau mot de passe</label><Input id="new-password" type="password" autoComplete="new-password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/><label htmlFor="confirm-password" className="block">Confirmer le mot de passe</label><Input id="confirm-password" type="password" autoComplete="new-password" minLength={8} required value={confirm} onChange={e=>setConfirm(e.target.value)}/>{error&&<p role="alert" className="text-destructive">{error}</p>}<Button disabled={busy} className="w-full">{busy?"Enregistrement…":"Enregistrer"}</Button></form>}</main></>;
}
