import { createFileRoute, useNavigate, Link } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { Scissors, ArrowRight, Save, Plus } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { SiteHeader } from "@/components/site-header";
import { useAuth } from "@/lib/auth-context";
import { supabase } from "@/integrations/supabase/client";
import { getAccount, createShop, openOwnedBoard } from "@/lib/queue.functions";
export const Route = createFileRoute("/_authenticated/account")({ head: () => ({meta:[{title:"Mon espace — NextChair"},{name:"description",content:"Votre profil et vos salons NextChair."},{property:"og:title",content:"Mon espace — NextChair"},{property:"og:description",content:"Gérez votre profil et retrouvez vos salons."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary"},{name:"robots",content:"noindex"}]}), component:Account });
function Account(){
 const {user}=useAuth();const navigate=useNavigate();const fetchAccount=useServerFn(getAccount);const create=useServerFn(createShop);const open=useServerFn(openOwnedBoard);
 const {data,error,isPending,refetch}=useQuery({queryKey:["account",user?.id],queryFn:()=>fetchAccount()});
 const [name,setName]=useState("");const [shopName,setShopName]=useState("");const [avg,setAvg]=useState(20);const [busy,setBusy]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{if(data)setName(data.profile.display_name);},[data]);
 async function save(e:React.FormEvent){e.preventDefault();if(!user)return;setBusy(true);setMessage("");const {error}=await supabase.from("profiles").update({display_name:name.trim()}).eq("id",user.id);setMessage(error?"Impossible d’enregistrer le profil.":"Profil enregistré.");setBusy(false);if(!error)refetch();}
 async function board(shopId:string){setBusy(true);setMessage("");try{const r=await open({data:{shopId}});localStorage.setItem(`nc-key-${r.slug}`,r.key);await navigate({to:"/s/$slug/board",params:{slug:r.slug},search:{key:r.key}});}catch{setMessage("Impossible d’ouvrir le salon.");}finally{setBusy(false);}}
 async function add(e:React.FormEvent){e.preventDefault();setBusy(true);setMessage("");try{const r=await create({data:{name:shopName,avgMinutes:avg}});localStorage.setItem(`nc-key-${r.slug}`,r.adminKey);await navigate({to:"/s/$slug/board",params:{slug:r.slug},search:{key:r.adminKey}});}catch{setMessage("Impossible de créer le salon. Réessayez.");}finally{setBusy(false);}}
 return <><SiteHeader/><main className="mx-auto max-w-6xl px-5 py-10"><p className="text-sm font-semibold uppercase text-primary">Mon espace</p><h1 className="mt-2 font-display text-5xl">Bonjour{name?`, ${name}`:""}.</h1>{isPending?<p className="mt-6">Chargement…</p>:error?<p role="alert" className="mt-6 text-destructive">Impossible de charger votre espace.<Button variant="link" onClick={()=>refetch()}>Réessayer</Button></p>:<div className="mt-8 grid gap-10 lg:grid-cols-[1fr_320px]"><section><h2 className="font-display text-3xl">Mes salons</h2><div className="mt-4 space-y-3">{data?.shops.length===0&&<p className="border-b py-5 text-muted-foreground">Vous n’avez pas encore de salon.</p>}{data?.shops.map(shop=><article key={shop.id} className="flex flex-wrap items-center justify-between gap-4 rounded-lg border bg-card p-5"><div className="flex items-center gap-3"><Scissors className="text-primary"/><div><h3 className="text-lg font-semibold">{shop.name}</h3><p className="text-sm text-muted-foreground">{shop.avg_cut_minutes} min par coupe</p></div></div><div className="flex gap-2"><Button variant="outline" asChild><Link to="/s/$slug" params={{slug:shop.slug}}>Vue client</Link></Button><Button disabled={busy} onClick={()=>board(shop.id)}>Ouvrir<ArrowRight/></Button></div></article>)}</div><form onSubmit={add} className="mt-8 border-t pt-6"><h2 className="flex items-center gap-2 font-display text-3xl"><Plus/>Ajouter un salon</h2><label htmlFor="shop-name" className="mt-4 block text-sm font-semibold">Nom du salon</label><Input id="shop-name" placeholder="Le Barbier du Quartier" value={shopName} onChange={e=>setShopName(e.target.value)} required maxLength={60} className="mt-2 h-12"/><label htmlFor="avg-cut" className="mt-4 block text-sm font-semibold">Durée moyenne d’une coupe : {avg} min</label><input id="avg-cut" type="range" min={5} max={60} step={5} value={avg} onChange={e=>setAvg(+e.target.value)} className="my-3 w-full accent-primary"/><Button disabled={busy||!shopName.trim()} type="submit">{busy?"Un instant…":"Créer la file"}<ArrowRight/></Button></form></section><section className="border-t pt-6 lg:border-l lg:border-t-0 lg:pl-8 lg:pt-0"><h2 className="font-display text-3xl">Mon profil</h2><form onSubmit={save} className="mt-4 space-y-4"><label htmlFor="profile-name" className="block text-sm font-semibold">Votre nom</label><Input id="profile-name" value={name} onChange={e=>setName(e.target.value)} required maxLength={60}/><p className="break-all text-sm text-muted-foreground">{user?.email}</p><Button variant="outline" type="submit" disabled={busy}><Save/>Enregistrer</Button></form><div className="mt-8 border-t pt-6"><h3 className="font-display text-2xl">Côté client</h3><Button variant="link" asChild className="mt-2 px-0"><Link to="/clients">Trouver mon barbier<ArrowRight/></Link></Button></div></section></div>}{message&&<p role="status" className="mt-5 text-sm">{message}</p>}</main></>;
}
